### ISSUE TITLE
API Project is not authorized error

### ISSUE THREAD

**Issue by dabnet795** [SamLewis0602/MMM-Traffic#78] opened 2019-08-19 14:38 UTC
Hello, I am receiving the following error.  I have Google Maps module loaded and working fine with the same API key.  Any thoughts

status: 'REQUEST_DENIED' }
ERROR: Google Maps API returned an error message:
{ error_message: 'This API project is not authorized to use this API.',
  routes: [],

The Mirror displays "Loading commute..." but never loads

**Comment by FaMiFisH** [comment] 2019-12-01 15:48
I am having the same problem :(

**Comment by gschmall** [comment] 2020-01-07 18:56
You need to turn on the directions api, which is a subset api to maps. Additionally, you will need to set up a google cloud billing account to activate your project you created to get your api key.

**Comment by SamLewis0602** [comment] 2020-03-04 19:54
@dabnet795 @FaMiFisH can either of you let me know if @gschmall 's answer solved your problem? I am going to dig back into this project this weekend. Sorry for the delayed response.

**Comment by SamLewis0602** [comment] 2020-03-08 05:51
I've confirmed this is due to not giving the API key proper permissions for the directions API. Closing this issue.

**Closed** 2020-03-12 13:52 UTC
